server:
  port: 8081

spring:
  application:
    name: project-rest-api
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_pm
    username: 'portfolio_pm@2319!'
    password: 'portfolio_pm@2319!'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  level:
    org.springdoc: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

clients:
  mock-members:
    base-url: http://localhost:8082
  mock-contract: 1
  mock-occupation: 3

api:
  auth:
    username: user
    password: user
    role: USER