server:
  port: 8082

spring:
  application:
    name: mock-members-api

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  level:
    org.springdoc: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
